apiVersion: 1

datasources:
  - name: k6
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: k6
    user: admin
    secureJsonData:
      password: admin123
    isDefault: true
